<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_3.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel_4.xacro" />

    <!-- 添加深度相机 -->
    <!-- d435i frame definition can be found at https://github.com/IntelRealSense/librealsense/blob/master/doc/d435i.md -->
    <xacro:include filename="$(find realsense_gazebo_description)/urdf/_d435i.urdf.xacro"/>
    <xacro:sensor_d435i parent="base_link" name="D435i_camera" topics_ns="D435i_camera"> 
      <origin xyz="0.325 0.0 0.475" rpy="0.0 0.22 0.0"/>
    </xacro:sensor_d435i>
    <!-- 添加深度相机 -->

    <!-- 添加机器人框架 -->
    <xacro:include filename="$(find profile_description)/urdf/profile.urdf.xacro"/>
    <xacro:profile
        parent="base_link" 
        xyz="0.0 0.0 0.05"
        rpy="0.0 0.0 0.0"
        scale="0.001 0.001 0.001"/>
    <!-- 添加机器人框架 -->

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

    <!-- <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" /> -->

    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin
                    xyz="0 0 0.0"
                    rpy="0 0 -1.57" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_simple.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0"
                    rpy="0 0 -1.57" />
          <geometry>
            <mesh
              filename="package://scout_description/meshes/scout_simple.stl" scale="0.001 0.001 0.001" />
          </geometry>
        </collision>
    </link>

    <!-- <joint name="chassis_link_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint> -->

    <link name="inertial_link">
        <inertial>
            <mass value="60" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->

    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->

    <xacro:scout_mini_wheel_1 wheel_prefix="front_left">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_1>

    <xacro:scout_mini_wheel_2 wheel_prefix="rear_left">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_2>
    <xacro:scout_mini_wheel_3 wheel_prefix="front_right">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_3>
    <xacro:scout_mini_wheel_4 wheel_prefix="rear_right">
    <!--<origin
           xyz="0 0 0"
           rpy="0 0 0" />-->
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_4>

    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />

    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find scout_description)/urdf/scout_mini.gazebo" />
    
  <xacro:arg name="gpu" default="false"/>
  <xacro:property name="gpu" value="$(arg gpu)" />
  <xacro:arg name="organize_cloud" default="false"/>
  <xacro:property name="organize_cloud" value="$(arg organize_cloud)" />
    
</robot>
